### ISSUE TITLE
Download Data Set - Filename and File Format.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/kcsf-index-2016#14]
The dataset we are downloading is SPSS proprietary data format. Is this OK? Is this what the client wants or do they want a version that's an open format like CSV?

Also, please make the filename more descriptive.  For example, instead of "dataset-en-2016.sav" have it as "KCSF - The Kosovar Civil Society Index - October 2016.sav"

**Comment by egzontina** [comment]
@georgeslabreche  We discussed for this with @dafinaolluri. I was asking the same thing. But she said that the data weren't supposed for everyone and they decided to leave it like that.

**Comment by egzontina** [comment]
@dafinaolluri  can you answer in this task please?

**Comment by dafinaolluri** [comment]
@georgeslabreche @egzontina I asked Nart, he said that SPSS is okay.

**Comment by dafinaolluri** [comment]
@egzontina Please see below the translations:

- [ ] EN: KCSF - The Kosovar Civil Society Index Questionnaire - October 2016;
- [ ] ALB: Indeksi Kosovar i Shoqerise Civile Pyetesori - Tetor 2016;
- [ ] SRB: Upitnik Kosovski indeks civilnog društva - Oktobar 2016

**Comment by egzontina** [comment]
@dafinaolluri  these translations are for Questionnaire or Dataset filenames?

**Comment by dafinaolluri** [comment]
@egzontina For Dataset Filenames
