### ISSUE TITLE
Questionnaire filenames needs to be more descriptive.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/kcsf-index-2016#16]
For example, in English, instead of "questionnaire-en-2015.pdf" it should be "KCSF - The Kosovar Civil Society Index Questionnaire - October 2016"

@dafinaolluri: why are the current questionnaire files named as 2015 instead of 2016?

**Comment by egzontina** [comment]
@dafinaolluri  can you answer in this task, please? Can you provide me the questionnaire filenames in three languages?

**Comment by dafinaolluri** [comment]
@egzontina Already asked from KCSF for the translation. I am waiting for their response.

**Comment by dafinaolluri** [comment]
Translations 

- [ ] Eng: The Kosovar Civil Society Index Questionnaire - October 2016
- [ ] Alb: Indeksi Kosovar i Shoqerise Civile Pyetesori - Tetor 2016
- [ ] Srb: Upitnik Kosovski indeks civilnog društva- Oktobar 2016
