### ISSUE TITLE
Include aggregate data for the UNDP Public Pulse indicators.

### ISSUE THREAD

**Issue by georgeslabreche** [opendatakosovo/kcsf-index-2016#5]
Currently only the cross-tabulated data is being presented.

**Comment by egzontina** [comment]
I have no data, I can't estimate this! @dafinaolluri

**Comment by dafinaolluri** [comment]
@egzontina forwarded to you in Gmail account.

**Comment by georgeslabreche** [comment]
@dafinaolluri please provide instructions on what to test here.

**Comment by dafinaolluri** [comment]
@georgeslabreche Egzontina had to see if there are changes with the original file that we had before, but nothing has changed.
